### PR TITLE
Switch to 00-tqu

### PR DESCRIPTION
**Pull request by stdweird**
Switch to Test::Quattor::Unittest and fix issues raised by perlcritic

Code changes are refactoring and clean up only and should not result
in any change in functionality.

### CODE REVIEW

**Comment by stdweird** [comment]
retest this please

**Comment by jrha** [comment]
Conflicts, needs rebase.

**Comment by stdweird** [comment]
@jrha rebased

**Comment by ned21** [comment]
I'm fine with the diff but following @jouvin's  point on a previous PR about commit logs, it's probably not clear to anyone who is not a core contributor why `Switch to Test::Quattor::Unittest` means a whole bunch of lines got modified (albeit in innocuous / clean up ways). Since we are expecting a lot of this commits, perhaps we could standardise on a wording? e.g.

```
Switch to Test::Quattor::Unittest and fix issues raised by perlcritic

Code changes are refactoring and clean up only and should not result
in any change in functionality.
```

**Comment by stdweird** [comment]
@ned21 done

**Comment by stdweird** [comment]
@ned21 or did you mena the commit message?

**Comment by ned21** [comment]
The commit message, please!

**Comment by stdweird** [comment]
@ned21 done

**Pull request merged**
