### PR TITLE
Make it possible to pass a logger to NCM::Blockdevices

### LINKED ISSUE #53: ncm-lib-blockdevices uses this_app directly instead of passing a logger during init
right now, we add 
`use NCM::Blockdevices;`
`$NCM::Blockdevices::this_app = $cmp;`
to the tests to make it work

### PR DESCRIPTION
**Pull request by kwaegema**
Replaces this_app, make it possible to pass the logger to the NCM objects from eg ncm-fstab and ncm-filesystems.

Fixes #53

### CODE REVIEW

**Comment by kwaegema** [comment]
fixes #53

**Comment by stdweird** [comment]
@kwaegema LGTM

**Comment by jrha** [comment]
LGTM too

**Comment by ned21** [comment]
The commit messages seem rather brief and a little reminiscent of [this](https://www.reviewboard.org/docs/codebase/dev/git/clean-commits/). Would you be able to combine some of these commits and then make each commit message much more detailed as to what is changing and why? Not that I am suggesting a "mega-commit" but a slightly better balance between one-commit that does everything and a lot of commits which are too trivial to necessitate a  detailed log message.

**Comment by kwaegema** [comment]
@ned21 did some refactoring of commits

**Comment by jrha** [comment]
Looks better, thanks

**Pull request merged**
