### PR TITLE
Add RHEL9 Anaconda version

### PR DESCRIPTION
**Pull request by aka7**

### CODE REVIEW

**Review by jouvin — APPROVED** [review]

**Comment by jouvin** [comment]
There is probably a related change needed in template-library-core. I'll try to check.

**Comment by aka7** [comment]
Thanks, please if you can let me know.
I'm bit confused as to how all this works. Aii is generating ks file and is
working fine for el9 without this anyway.

**Comment by jouvin** [comment]
The point is (if I remember correctly) that the constants defined in aii-ks are compared against the version defined in the profile to adjust the rendering of the Kickstart file based on Anaconda version. Thus you need a template that defines the Anaconda version for the OS version you use. In template-library-core, it is the OS variant in `quattor/aii/ks/variants`.

It seems @jrha already took care of doing it in https://github.com/quattor/template-library-core/commit/95c1e28e3071bf993ed9d6a038c55eb96cad2e37.

**Comment by jrha** [comment]
The AII part was done in https://github.com/quattor/aii/pull/341.

**Review by jrha — APPROVED** [review]

**Pull request merged**
