### PR TITLE
Add github action for tests

### PR DESCRIPTION
**Pull request by wpoely86**

### CODE REVIEW

**Comment by wpoely86** [comment]
Output can be found at https://github.com/wpoely86/ncm-lib-blockdevices/actions/runs/3592056181

One test is actually failing.

**Comment by ned21** [comment]
Looks like a warning turned into an error? 

```
src/test/perl/partition_gpt.t ................... 
...
not ok 26 - Perl warning: Use of uninitialized value in join or string at /__w/ncm-lib-blockdevices/ncm-lib-blockdevices/target/dependency/build-scripts/Test/Quattor.pm line 348.
[13899](https://github.com/wpoely86/ncm-lib-blockdevices/actions/runs/3592056181/jobs/6047325328#step:8:13900)
# 
[13900](https://github.com/wpoely86/ncm-lib-blockdevices/actions/runs/3592056181/jobs/6047325328#step:8:13901)
not ok 27 - Perl warning: Use of uninitialized value $p in concatenation (.) or string at /__w/ncm-lib-blockdevices/ncm-lib-blockdevices/target/lib/perl/NCM/Blockdevices.pm line 511.
[13901](https://github.com/wpoely86/ncm-lib-blockdevices/actions/runs/3592056181/jobs/6047325328#step:8:13902)
```

The second problem looks fixable: `my $p = abs_path($self->devpath);` needs to handle devpath being undef or similar?

**Comment by wpoely86** [comment]
I'm not very fluent in Perl (to say the least) but are these really 'errors' or just poor tests?

I've added github actions to almost all quattor repos and a bunch of them fail, often with 'Use of uninitialized value '. 
- ncm-ncd: https://github.com/wpoely86/ncm-ncd/actions/runs/3592724123/jobs/6048779571
- CAF: https://github.com/wpoely86/CAF/actions/runs/3592767878/jobs/6048881615

**Comment by stdweird** [comment]
certain classes of perl warnings are considered errors. it's odd you see them with centos7 perl though; usually they pop up when eg i run the tests on my laptop with a new fedora (and thus perl) release

**Comment by wpoely86** [comment]
I've also tried using rockylinux 8 as base image for the configuration-core tests and same deal there: https://github.com/wpoely86/configuration-modules-core/actions/runs/3593095946/jobs/6049613610
I guess Perl has gotten more strict on these warnings?

**Review by jrha — APPROVED** [review]
The test config looks good, so happy to merge this.
We need to put some effort into improving our code so fewer errors are thrown, maybe this will encourage us.

**Comment by wpoely86** [comment]
I've opened PRs to the two remaining repos without test and one which the current tests fail.

**Pull request merged**
