### PR TITLE
LV and LVM support force in kickstart

### LINKED ISSUE #45: LV: lvcreate --wipesignatures y wrong syntax
should be -W y or --wipesignature y instead

### PR DESCRIPTION
**Pull request by stdweird**
Also fixes #45

### CODE REVIEW

**Comment by stdweird** [comment]
This is based on #40 , so that one needs merged in first

Need to set 
```pan
"/system/aii/osinstall/ks/lvmforce" = true;
```

(e.g. in the EL7 variants template)

**Comment by stdweird** [comment]
test this please

**Comment by jrha** [comment]
Needs rebasing?

**Comment by stdweird** [comment]
@jrha rebased and tests happy

**Comment by jouvin** [comment]
FYI, I tested this PR (and the other one required) successfully except the last commit to fix the interactive mode with --wipe-signature....

**Comment by jrha** [comment]
You didn't test the last commit or it didn't work?

**Comment by jouvin** [comment]
I didn't test it. I was about to do it...

**Comment by jrha** [comment]
Ok cool

**Pull request merged**
