### PR TITLE
Filesystem.pm: add support for vfat filesystems

### LINKED ISSUE #71: Filesystem.pm: add support for fat32
fat32 (vfat) support is required to format the boot partition used by UEFI. This partition must be formatted and mounted before the installation.

Contributes to https://github.com/quattor/aii/issues/97.

After fixing this issue, define the `fstype` and `mountpoint` in template-library-standard `filesystem/config.pan` `DISK_VOLUME_PARAMS`.

### PR DESCRIPTION
**Pull request by jouvin**
Fixes #71

### CODE REVIEW

**Comment by jouvin** [comment]
I checked that the generated KS is ok but I didn't try a real deployment yet...

**Comment by stdweird** [comment]
no problem, i'll give it a try soon (but i doubt there will any issue)

**Comment by stdweird** [comment]
@jouvin and thx!

**Comment by stdweird** [comment]
@rhumroux @samary is required for UEFI tests

**Pull request merged**
