### PR TITLE
Make unittest pass with 1.40 buildtools

### PR DESCRIPTION
**Pull request by stdweird**

### CODE REVIEW

**Comment by stdweird** [comment]
@jrha i totally missed the issue that the current master of `ncm-lib-blockdevices` doesn't pass the tests anymore. this is an update with fixes for the most recent build tools.
This adds no new features (well, the added close might fix a race condition)

**Comment by stdweird** [comment]
2 of the 3 commits come from another branch, that's why i prefer not to squash them

**Comment by ned21** [comment]
LGTM, will leave to @jrha  to merge given that we are close to release.

**Comment by stdweird** [comment]
@ned21 i think this is blocking the release :smile: (current master doesn't pass the unittests anymore on recent perl)

**Comment by jrha** [comment]
Many thanks!

**Pull request merged**
