### PR TITLE
LV: add chunksize and cachemode options

### PR DESCRIPTION
**Pull request by kwaegema**
also https://github.com/quattor/template-library-core/pull/107

### CODE REVIEW

**Comment by stdweird** [comment]
@kwaegema tested?

**Comment by stdweird** [comment]
@kwaegema i've moved this to 16.4 as this is an enhancement, not a bugfix
you want me to add this to qmmpack?

**Comment by kwaegema** [comment]
@stdweird I rolled out test2200 using these features and it works 
can be added to qmmpack, thanks

**Comment by jrha** [comment]
LGTM, but not a LV expert

**Comment by jouvin** [comment]
LGTM too. Probably better if @stdweird merges it as it seems you are using it already and thus can assess better than me if it works as expected!

**Comment by stdweird** [comment]
yes, works as expected.

**Pull request merged**
