### PR TITLE
bump build-tools to 1.54

### PR DESCRIPTION
**Pull request by stdweird**

### CODE REVIEW

**Comment by jrha** [comment]
@hpcugentbot retest this please

**Comment by jrha** [comment]
@hpcugentbot test this please

**Comment by jrha** [comment]
Poop, webhook is failing because Jenkins certificate has apparently expired.

**Comment by jrha** [comment]
@stdweird any way to trigger the build on the Jenkins server?

**Comment by jrha** [comment]
@hpcugentbot test this please

I have disabled SSL validation for the time being

**Comment by stdweird** [comment]
@jrha we were suppsoed to migrate to new jenkins server, and i lost track of it. i'll try to continue that work

**Pull request merged**
